### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by tktm515** [tktm515/protospace-34463#1]
#URL
https://protospace-34463.herokuapp.com/

**Comment by vesper1102609** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

[修正依頼箇所]
**●コメントでフォームを空のまま投稿しようとするとエラーが発生します。**
フォームを空のまま投稿しようとすると、投稿できずにそのページに留まるように修正しましょう。

フォームが空の状態で投稿
![image](https://user-images.githubusercontent.com/49742444/108179437-f6f88c00-7148-11eb-8493-8e483ebd4822.png)

エラー発生
![image](https://user-images.githubusercontent.com/49742444/108179458-fa8c1300-7148-11eb-9374-a0298a06d022.png)

**Comment by tktm515** [comment]
お疲れ様です。
上記でのご指摘の件、修正しておりますのでご確認よろしくお願い致します。

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
